/**
 * The typed shape of `src/generated/project-manifest.json`.
 *
 * This is the ONLY place the website may obtain an engineering count or an
 * implementation status. No component may hardcode a number that describes the
 * project, and `tests/unit/content-integrity.test.ts` enforces that by scanning
 * the component tree for the manifest's own values appearing as literals.
 *
 * Generated by `scripts/generate-project-manifest.ts` from source-controlled
 * repository files. Every field carries the path it was read from, so a reader
 * of the site can trace any number back to the file that proves it.
 */

/** Where a manifest value came from. Rendered by <SourceLink>. */
export interface EvidenceSource {
  /** Repository-relative path, e.g. `powerbi/validation/model_expectations.json`. */
  readonly path: string
  /** What in that file was read, e.g. `relationship_count`. */
  readonly field: string
}

/** A number the site displays, with its provenance attached. */
export interface SourcedCount {
  readonly value: number
  readonly label: string
  /** Short clause explaining what the number counts. No marketing language. */
  readonly detail: string
  readonly sources: readonly EvidenceSource[]
}

/**
 * The project's status vocabulary. Deliberately narrow, and deliberately
 * without a value that means "nearly done".
 *
 *  complete           Exists, runs, and its own exit criteria are met.
 *  in-progress        Work has started and is not finished.
 *  pending-external   Finished on this side; waiting on a system outside this
 *                     repository. Never rendered as a pass.
 *  blocked            Cannot start until a named condition clears.
 *  deferred           In the target architecture, outside the current roadmap.
 *  not-started        Committed scope, no work done.
 */
export type StatusLevel =
  | 'complete'
  | 'in-progress'
  | 'pending-external'
  | 'blocked'
  | 'deferred'
  | 'not-started'

/** A real-engine validation path, per ADR-0008. */
export interface EngineValidation {
  readonly id: 'desktop' | 'fabric'
  readonly label: string
  /** Verbatim `overall_result` from the evidence file. */
  readonly overallResult: string
  readonly status: StatusLevel
  /** ISO timestamp, or null when the engine has never run. */
  readonly validatedAt: string | null
  readonly passedCheckCount: number
  readonly failedCheckCount: number
  /** The honest note from the evidence file, trimmed to one or two sentences. */
  readonly note: string
  readonly evidencePath: string
  readonly procedurePath: string
}

/** A lifecycle phase from ARCHITECTURE.md section 27. */
export interface LifecyclePhase {
  readonly number: number
  readonly name: string
  readonly status: StatusLevel
  /** One sentence. What the phase covers. */
  readonly summary: string
  /** One sentence. Why it holds the status it holds. */
  readonly statusReason: string
  readonly exitCriteria: readonly string[]
}

/** A delivery increment from docs/requirements/PHASE_2_BACKLOG.md. */
export interface DeliveryIncrement {
  readonly id: string
  readonly name: string
  readonly status: StatusLevel
  readonly statusReason: string
  readonly lifecyclePhase: number
  readonly blockingGate: string | null
}

/** A scope gate from ARCHITECTURE.md section 28. */
export interface Gate {
  readonly id: string
  readonly name: string
  readonly verdict: 'OPEN' | 'CLOSED'
  /** ISO date the verdict was recorded, or null when no review exists. */
  readonly recordedOn: string | null
  /** The document holding the written verdict, or null when none exists. */
  readonly verdictPath: string | null
  readonly conditions: readonly GateCondition[]
}

export interface GateCondition {
  readonly ordinal: number
  readonly condition: string
  readonly met: boolean
  readonly evidence: string
}

/** One row of the evidence ledger on the home page and the status page. */
export interface EvidenceRecord {
  readonly id: string
  readonly label: string
  readonly kind: 'static' | 'real-engine' | 'reconciliation' | 'test' | 'privacy'
  readonly status: StatusLevel
  /** What was actually checked. Concrete, with counts where they exist. */
  readonly detail: string
  readonly sources: readonly EvidenceSource[]
}

/** Case-study gate evaluation, computed at build time. */
export interface CaseStudyGate {
  readonly unlocked: boolean
  readonly flagEnabled: boolean
  readonly gate2Open: boolean
  readonly readinessDocumentExists: boolean
  readonly requiredContentPresent: boolean
  readonly requiredScreenshotsPresent: boolean
  /** Human-readable reasons the case study is locked. Empty when unlocked. */
  readonly blockingReasons: readonly string[]
}

export interface ProjectManifest {
  readonly schema: 'arpi.project_manifest/1'
  /** Set from the build environment, not from the clock, so output is stable. */
  readonly generatedFromCommit: string
  /** Which config profile the row counts describe. */
  readonly dataProfile: string

  readonly project: {
    readonly name: string
    readonly shortName: string
    readonly author: string
    readonly dealershipGroup: string
    readonly repositoryUrl: string
    readonly licence: string
  }

  /** The credibility strip. Every entry is source-backed. */
  readonly counts: {
    readonly dealerships: SourcedCount
    readonly dimensions: SourcedCount
    readonly facts: SourcedCount
    readonly reportingViews: SourcedCount
    readonly governedKpis: SourcedCount
    readonly semanticRelationships: SourcedCount
    readonly daxMeasures: SourcedCount
    readonly semanticTables: SourcedCount
    readonly importedTables: SourcedCount
    readonly measureTables: SourcedCount
    readonly supportingMeasures: SourcedCount
    readonly reconciliations: SourcedCount
    readonly dataQualityChecks: SourcedCount
    readonly staticAssertions: SourcedCount
    readonly sqlScripts: SourcedCount
  }

  readonly semanticModel: {
    readonly projectName: string
    readonly storageMode: string
    readonly sourceSchema: string
    readonly databaseIdentity: string
    readonly markedDateTable: string
    readonly activeRelationships: number
    readonly inactiveRelationships: number
    readonly bidirectionalRelationships: number
    readonly manyToManyRelationships: number
    readonly staticValidationStatus: StatusLevel
    readonly realEngineStatus: StatusLevel
    readonly dashboardPageCount: number
  }

  readonly engines: readonly EngineValidation[]
  readonly lifecyclePhases: readonly LifecyclePhase[]
  readonly increments: readonly DeliveryIncrement[]
  readonly gates: readonly Gate[]
  readonly evidence: readonly EvidenceRecord[]
  readonly caseStudy: CaseStudyGate

  readonly dataset: {
    readonly profile: string
    readonly randomSeed: number
    readonly reportingDateRange: { readonly first: string; readonly last: string }
    readonly synthetic: true
    readonly containsPii: false
  }
}
