/**
 * The application frame: the one way this site shows a piece of software.
 *
 * WHY IT EXISTS
 * -------------
 * Before this component the home page linked to four working experiences - the
 * inventory explorer, the architecture explorer, the data model explorer and the
 * KPI catalogue - and showed none of them. A visitor read thirteen chapters of
 * description and had to take on trust that anything ran. The single largest
 * improvement available to this site was to put the product on the page.
 *
 * The frame is what makes that legible. A screenshot dropped into a document
 * reads as an illustration; the same screenshot inside a chrome bar with a route
 * on it reads as an application. It is the same device `OperatingView` already
 * used inline, extracted so that four call sites share one definition instead of
 * each rebuilding the chrome.
 *
 * WHAT IT FRAMES
 * --------------
 * Anything. `children` may be a live interactive island (the hero's store
 * switcher), a captured image of a real route (`<ApplicationImage>`), or an SVG
 * composition. The frame makes no assumption about its contents beyond giving
 * them a surface and a label.
 *
 * A SERVER COMPONENT
 * ------------------
 * No state, no effects, no motion of its own. A client island passed as
 * `children` stays the only client boundary, which is what keeps the frame free
 * on routes that use it for a static capture.
 *
 * HONESTY IS A PROP, NOT A CONVENTION
 * -----------------------------------
 * `provenance` is required and is rendered in the chrome, always. Every frame on
 * this site says in words what a reader is looking at: live sanitized data, a
 * capture of a named route, repository-derived evidence, or a fictional
 * visualisation. A product frame that does not say what it is is the artefact
 * this project exists to argue against.
 */
import type { ReactNode } from 'react'

import { cx } from '@/lib/utils'

/**
 * What a reader is looking at. Rendered as words in the chrome bar, never as a
 * colour or an icon alone.
 */
export type FrameProvenance =
  /** A live, interactive surface rendering data that shipped with the page. */
  | 'live'
  /** A still capture of a route of this application, taken from a real build. */
  | 'capture'
  /** A drawn composition, generated from design tokens rather than photographed. */
  | 'drawn'
  /** Repository evidence, regenerated by the build. */
  | 'evidence'

const PROVENANCE_LABEL: Record<FrameProvenance, string> = {
  live: 'Live in this page',
  capture: 'Captured from the running application',
  drawn: 'Drawn composition, not a photograph',
  evidence: 'Generated from repository evidence',
}

export interface ApplicationFrameProps {
  /** The surface's name, shown in the chrome. Not the section heading. */
  title: string
  /** The route the surface belongs to, shown as a monospace path. */
  path?: string
  provenance: FrameProvenance
  /**
   * One short clause qualifying the provenance, for a surface that needs it -
   * "sanitized reference data", "no engine has evaluated these measures".
   */
  note?: string
  /** Rendered under the frame as a figure caption. */
  caption?: ReactNode
  children: ReactNode
  className?: string
  /** Applied to the body element, for a surface that manages its own padding. */
  bodyClassName?: string
  /**
   * An accessible name for the figure. Supply one whenever the frame is not
   * already introduced by a nearby heading.
   */
  label?: string
}

export function ApplicationFrame({
  title,
  path,
  provenance,
  note,
  caption,
  children,
  className,
  bodyClassName,
  label,
}: ApplicationFrameProps) {
  return (
    <figure className={cx('m-0 flex flex-col gap-3', className)} aria-label={label}>
      <div
        className={cx(
          'overflow-hidden rounded-frame border border-line-strong',
          'bg-canvas shadow-xl inset-shadow-top'
        )}
      >
        {/* The chrome. Three dots, a name, a path and the provenance. The dots
            are decorative and removed from the accessibility tree; the
            provenance is words, so removing all colour loses nothing. */}
        <div className="flex flex-col gap-2 border-b border-line bg-surface-sunken/70 px-4 py-3 sm:flex-row sm:items-center sm:justify-between sm:gap-5 sm:px-5">
          <div className="flex min-w-0 items-center gap-3">
            <span aria-hidden="true" className="flex shrink-0 items-center gap-1.5">
              <span className="inline-block size-1.5 rounded-pill bg-accent" />
              <span className="inline-block size-1.5 rounded-pill bg-model" />
              <span className="inline-block size-1.5 rounded-pill bg-line-strong" />
            </span>
            <span className="truncate font-display text-sm font-semibold tracking-tight text-ink sm:text-base">
              {title}
            </span>
            {path ? (
              <code className="hidden shrink-0 rounded-sm border border-line-subtle bg-canvas px-1.5 py-0.5 font-mono text-2xs text-ink-faint sm:inline">
                {path}
              </code>
            ) : null}
          </div>
          <p className="min-w-0 font-mono text-2xs leading-normal text-ink-faint sm:text-right">
            {PROVENANCE_LABEL[provenance]}
            {note ? `. ${note}` : '.'}
          </p>
        </div>

        <div className={cx('relative', bodyClassName)}>{children}</div>
      </div>

      {caption ? (
        <figcaption className="max-w-prose text-xs leading-normal text-ink-faint">
          {caption}
        </figcaption>
      ) : null}
    </figure>
  )
}

/* -------------------------------------------------------------------------- */
/* ApplicationImage                                                            */
/* -------------------------------------------------------------------------- */

export interface ApplicationImageProps {
  /** Path under `public/`, produced by `scripts/capture-product-media.ts`. */
  src: string
  /**
   * What the capture shows, for a reader who cannot see it. Never "screenshot of
   * the inventory explorer": describe what is on screen.
   */
  alt: string
  /** The captured pixel dimensions. Required, so the box is reserved. */
  width: number
  height: number
  className?: string
}

/**
 * A captured route, sized so it reserves its own space.
 *
 * WHY A PLAIN `<img>` AND NOT `next/image`
 * ----------------------------------------
 * `next/image` earns its keep when it can resize a source into several
 * candidates and serve the smallest one that fits. These four files are already
 * the only size they are ever displayed at, already WebP, and already under
 * 120 kB each. Routing them through the optimizer would add a runtime dependency
 * on `sharp` inside the Railway standalone image - which `next.config.ts`
 * deliberately does not configure a loader for - in exchange for nothing.
 *
 * The two things `next/image` is genuinely for are done here explicitly:
 * `width` and `height` are intrinsic, so the box is reserved and the frame
 * causes no layout shift; and `loading="lazy"` keeps every capture off the
 * critical path, because none of them is above the fold.
 */
export function ApplicationImage({
  src,
  alt,
  width,
  height,
  className,
}: ApplicationImageProps) {
  return (
    /* Pre-sized, pre-encoded WebP served without the optimizer on purpose. The
       reasoning is in the doc comment above; the intrinsic dimensions and the
       lazy attribute do the two jobs `next/image` would have done here. */
    // eslint-disable-next-line @next/next/no-img-element
    <img
      src={src}
      alt={alt}
      width={width}
      height={height}
      loading="lazy"
      decoding="async"
      className={cx('block h-auto w-full bg-surface-sunken', className)}
    />
  )
}
