#!/usr/bin/env tsx
/**
 * Capture the home page's product tour media from the running application.
 *
 * WHY THESE FILES ARE COMMITTED WHEN THE REVIEW SCREENSHOTS ARE NOT
 * -----------------------------------------------------------------
 * `capture-review-screenshots.ts` produces a hundred-odd images that exist for
 * the duration of one pull request, and `portfolio/docs/VISUAL_REVIEW.md`
 * records the decision not to keep them: a baseline set nobody re-approves
 * becomes a rubber stamp.
 *
 * These five are different in kind. They are content: the product tour shows what
 * the operating console, the inventory explorer, the architecture explorer, the
 * data model explorer and the KPI catalogue actually look like, because a
 * portfolio that only links to its own work asks a reviewer to click five times
 * before seeing anything. They have to be in the repository for the same reason
 * the favicon is, and they are regenerated by hand from this script rather than on
 * every build, for the same reason `render-raster-assets.ts` is not in `build`:
 * downloading a browser on every CI run to produce five files that did not
 * change is a cost with no benefit.
 *
 * Usage, against a production build:
 *
 *   npm run build
 *   npx next start -p 3111 &
 *   ARPI_MEDIA_BASE_URL=http://localhost:3111 npm run media
 *
 * A trailing argument re-takes one target and leaves the rest untouched:
 *
 *   ARPI_MEDIA_BASE_URL=http://localhost:3111 npm run media -- executive
 *
 * WHAT IT DOES NOT DO
 * -------------------
 * It does not compose, retouch, annotate or recolour anything. Every file is a
 * straight capture of a route of this application at a stated viewport, which is
 * the only kind of product image this project is allowed to publish. A mocked-up
 * dashboard would be indistinguishable to a reader from a real one, and this
 * site's entire argument is that the difference matters.
 */
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import { chromium, type Page } from '@playwright/test'
import sharp from 'sharp'

import { resolveChromiumPath } from './chromium.ts'

const HERE = dirname(fileURLToPath(import.meta.url))
const PORTFOLIO = resolve(HERE, '..')
const OUT = join(PORTFOLIO, 'public/media')
const BASE = process.env.ARPI_MEDIA_BASE_URL ?? 'http://localhost:3111'

/**
 * The capture viewport.
 *
 * 1440 wide because that is where the explorers use their full two-column
 * layout, and it is the width the responsive matrix already treats as the
 * reference desktop. The device scale factor is 2, so the WebP is encoded from a
 * 2880px-wide capture and stays sharp on a high-density display at the roughly
 * 720px the tour renders it at.
 */
const VIEWPORT = { width: 1440, height: 1000 } as const
const SCALE = 2

/** The encoded width. Twice the largest size the tour ever displays. */
const OUTPUT_WIDTH = 1600

/**
 * The tallest a frame may be, in CSS pixels, before it is cropped.
 *
 * A capture taller than this stops being a product frame and becomes a page
 * scroll: the KPI catalogue is thousands of pixels tall and photographing all of
 * it would produce a strip nobody can read at tour size. Cropping to the top of
 * the surface is honest - it is what a visitor sees when they arrive - and the
 * route itself is one click away.
 */
const MAX_HEIGHT = 820

interface Target {
  /** Output file name under `public/media/`. */
  readonly file: string
  readonly route: string
  /**
   * The element to photograph. Every explorer names an id on its own root.
   *
   * OMITTED FOR THE OPERATING CONSOLE, and the omission is the honest choice
   * rather than a shortcut. The console's product is its whole first viewport —
   * the navigation rail, the control band, the KPI rail and the first row of
   * modules — and no single element contains all four: the rail is a sibling of
   * `<main>` in the group layout. Photographing `#main-content` would crop the
   * navigation out of a picture of an application, which is the one part of the
   * frame a reader uses to judge that it IS an application.
   *
   * So the shot is the viewport itself, from the top of the document, which is
   * literally what a visitor sees on arrival — the same thing the first-viewport
   * contract in `tests/e2e/executive-workspace.spec.ts` asserts by measurement.
   */
  readonly selector?: string
  /** Crop height in CSS pixels. Defaults to {@link MAX_HEIGHT}. */
  readonly height?: number
  /**
   * Work to do before the shot: open a panel, select a node, type a filter.
   * Kept to interactions a visitor would perform, never to hiding a defect.
   *
   * Every one of these exists because the default state of an explorer is an
   * empty right-hand panel saying "no component selected", and a product frame
   * whose panel is empty demonstrates that the surface exists rather than that
   * it does anything.
   */
  readonly prepare?: (page: Page) => Promise<void>
}

const TARGETS: readonly Target[] = [
  {
    /*
     * THE OPERATING CONSOLE, AND WHY IT IS IN THE TOUR AT ALL.
     *
     * The tour showed the four explorers and not the application they exist to
     * explain. `ADR-0015` had made the console the front door in the meantime, so
     * the one route a reader lands on was the one route the tour did not show.
     *
     * It is captured at the DEFAULT query — no store, no period, no comparison
     * override — because the default is what a visitor arriving at `/` gets, and a
     * frame taken from a filter state a reader cannot reproduce by clicking the
     * link under it is a composed image with extra steps.
     */
    file: 'executive-command-center.webp',
    route: '/',
    /*
     * The whole viewport, not the 820 the explorers crop to. The console's first
     * viewport is a CONTRACT rather than a layout accident — the control band, the
     * KPI rail whole, and three modules of geometry — and a crop that stopped
     * short of the third module would photograph the one part of the surface the
     * project measures and publish the part it does not.
     */
    height: VIEWPORT.height,
  },
  {
    file: 'inventory-explorer.webp',
    route: '/inventory',
    selector: '#inventory-explorer',
    height: 780,
  },
  {
    file: 'architecture-explorer.webp',
    route: '/architecture',
    selector: '#architecture-explorer',
    height: 640,
    prepare: async (page) => {
      await page
        .getByRole('option', { name: /warehouse/i })
        .first()
        .click()
    },
  },
  {
    file: 'data-model-explorer.webp',
    route: '/data-model',
    selector: '#data-model-explorer',
    height: 820,
    prepare: async (page) => {
      await page
        .getByRole('option', { name: /^Vehicle sale\./i })
        .first()
        .click()
    },
  },
  {
    file: 'kpi-catalogue.webp',
    route: '/kpis',
    selector: '#kpi-catalogue',
    height: 780,
    prepare: async (page) => {
      await page
        .getByRole('button', { name: /retail units sold/i })
        .first()
        .click()
    },
  },
]

/**
 * Which targets this run writes. Every one, unless the command line names some.
 *
 * WHY A FILTER EXISTS
 * -------------------
 * The encoder is not byte-reproducible across versions, so re-running the whole
 * set to add one capture rewrites four files that did not change and puts four
 * unreviewable binary diffs in the pull request that added the fifth. Naming the
 * target keeps the diff to the thing that actually moved:
 *
 *   ARPI_MEDIA_BASE_URL=http://localhost:3111 npm run media -- executive
 *
 * A name that matches nothing is an error rather than a silent no-op, because
 * the failure it would otherwise produce is "the capture I asked for did not
 * change" discovered at review time.
 */
function selectTargets(names: readonly string[]): readonly Target[] {
  if (names.length === 0) return TARGETS

  return names.map((name) => {
    const match = TARGETS.find((target) => target.file.includes(name))
    if (!match) {
      throw new Error(
        `no capture target matches "${name}". Available: ` +
          TARGETS.map((target) => target.file).join(', ')
      )
    }
    return match
  })
}

async function main(): Promise<void> {
  mkdirSync(OUT, { recursive: true })

  const targets = selectTargets(process.argv.slice(2))

  const browser = await chromium.launch({ executablePath: resolveChromiumPath() })
  const context = await browser.newContext({
    viewport: { width: VIEWPORT.width, height: VIEWPORT.height },
    deviceScaleFactor: SCALE,
    // The captures are of a static, animation-free state. Asking for reduced
    // motion means no reveal is mid-transition when the shutter opens, which is
    // what produced half-faded sections in the first run.
    reducedMotion: 'reduce',
  })

  try {
    for (const target of targets) {
      const page = await context.newPage()
      await page.goto(`${BASE}${target.route}`, { waitUntil: 'networkidle' })

      // A viewport capture still waits for the route's own landmark, so a shot is
      // never taken of a document that has not finished rendering its content.
      const element = page.locator(target.selector ?? 'main')
      await element.waitFor({ state: 'visible', timeout: 30_000 })
      if (target.prepare) await target.prepare(page)

      // Bring the surface to the top of the viewport, then measure it there.
      // Measuring before scrolling gives a box whose `y` is off-screen and a
      // clip Playwright rejects.
      await element.evaluate((node) => {
        node.scrollIntoView({ block: 'start', behavior: 'instant' })
        window.scrollBy(0, -24)
      })
      await page.waitForTimeout(250)

      const height = target.height ?? MAX_HEIGHT
      let clip: { x: number; y: number; width: number; height: number } = {
        x: 0,
        y: 0,
        width: VIEWPORT.width,
        height,
      }

      if (target.selector === undefined) {
        // The viewport, from the top of the document. `scrollIntoView` above may
        // have moved it, so the page is returned to the origin first: the shot is
        // of an arrival, not of a scroll position.
        await page.evaluate(() => {
          window.scrollTo(0, 0)
        })
        await page.waitForTimeout(100)
      } else {
        const box = await element.boundingBox()
        if (!box) throw new Error(`${target.selector} has no box on ${target.route}`)
        clip = {
          x: Math.max(0, Math.round(box.x)),
          y: Math.max(0, Math.round(box.y)),
          width: Math.min(Math.round(box.width), VIEWPORT.width),
          height: Math.min(Math.round(box.height), height),
        }
      }

      const png = await page.screenshot({ type: 'png', clip })

      const encoded = await sharp(png)
        .resize({ width: OUTPUT_WIDTH, withoutEnlargement: true })
        .webp({ quality: 80, effort: 6 })
        .toBuffer()

      writeFileSync(join(OUT, target.file), encoded)
      const meta = await sharp(encoded).metadata()
      console.log(
        `  ${target.file.padEnd(28)} ${String(meta.width)}x${String(meta.height)}  ` +
          `${String(Math.round(encoded.byteLength / 1024))} kB  from ${target.route}`
      )

      await page.close()
    }
  } finally {
    await context.close()
    await browser.close()
  }

  console.log(`\nproduct media written to public/media/ from ${BASE}`)
}

main().catch((error: unknown) => {
  console.error(error)
  process.exitCode = 1
})
