"""Generator for ``warehouse.fact_sales_target`` -- the operating plan, not the result.

WHAT THIS ENTITY IS
-------------------
One row per store, per governed target scope, per targeted KPI, per calendar month,
carrying the month's committed goal (``target_value``) and its stretch goal
(``stretch_target_value``). It is the first management-planning domain in ARPI and it
is promoted by delivery increment ``DASH.5``.

Every value here is a **synthetic internal operating goal for the fictional Granite Auto
Group**. It is not an industry benchmark, not a manufacturer objective, not a market
standard and not a real dealership's plan. Nothing in this module may be read as
"good", "average" or "recommended".

THE RULE THAT SHAPES THE WHOLE MODULE: NO OUTCOME LEAKAGE
---------------------------------------------------------
A plan that is computed from the result it is supposed to measure is not a plan. If
this module read ``sale_event`` and emitted ``actual * 1.05``, every attainment figure
on the console would be a restatement of the same number and the demonstration would
be worthless -- worse, it would be dishonest, because the page would present a
tautology as a management measurement.

So this module **must not import, call, or otherwise consume any realized sales
output**. Its inputs are exogenous planning assumptions only:

  * the store's operating model and planning scale (:data:`STORE_PLANNING_BASELINE`),
    the same class of fixed store-scale assumption ``arpi.generation.vehicle`` uses;
  * the governed selling-day calendar, rebuilt from :func:`build_calendar_rows`, which
    is deterministic, seed-free and owned by ADR-0002;
  * a planning seasonality shape (:data:`TARGET_MONTH_SEASONALITY`) declared here as a
    project default;
  * seeded planning variation drawn from the ARPI master seed through
    :func:`arpi.utilities.seeding.rng_for`.

``tests/unit/test_sales_target_generation.py`` asserts the module's import graph
contains no realized-sales module, so the rule is enforced rather than promised.

THE SCOPE MODEL, AND WHY DEPARTMENTS TARGET GROSS COMPONENTS
------------------------------------------------------------
``SQ-31`` asks whether the group is hitting its targets *by store and by department*,
so the scope model has to answer both halves without double counting.

  * **Store scope** targets the two headline store measures: retail units
    (``KPI-SLS-001``) and total gross (``KPI-GRS-003``).
  * **Department scope** targets the two *components* of total gross, which partition
    it exactly: the Sales department owns front-end gross (``KPI-GRS-001``) and the
    Finance department owns back-end gross (``KPI-GRS-002``). ``fact_vehicle_sale``
    enforces ``total_gross = front_end_gross + back_end_gross`` as a CHECK constraint,
    so the two department actuals sum to the store actual with no overlap and no gap.
    The generator makes the two department *targets* sum to the store total-gross
    target for the same reason.
  * **Retail units are deliberately store-scope only.** A retail unit is delivered
    once. Attributing it to the Sales department reproduces the store target, and
    attributing it to Finance as well would count the same car twice. Dealership
    practice is the same: F&I measures are computed *per* the sales department's unit
    count, not on a second unit count of their own.
  * **Employee scope** is part of the permanent vocabulary and is physically supported
    by ``warehouse.fact_sales_target`` (nullable ``employee_key``, CHECK-coupled to the
    scope type, foreign key to ``warehouse.dim_employee``). It is **not generated by
    DASH.5**: no registered stakeholder question requires employee-scope targets,
    ``DASH.11`` owns the employee-performance surface, and Gate 4 forbids adding data a
    question does not require. The decision is recorded in
    ``docs/source-to-target/STM-016-fact-sales-target.md`` section 6.

EXACT ARITHMETIC
----------------
Every emitted money and unit value is a :class:`decimal.Decimal` quantized to two
places. No Python float ever touches a target: the planning multipliers are floats
because they are dimensionless shape parameters, but they are converted to
``Decimal`` before they multiply a currency or a unit count, and the result is
quantized with :data:`decimal.ROUND_HALF_UP` exactly once.
"""

from __future__ import annotations

import random
from dataclasses import dataclass
from datetime import date
from decimal import ROUND_HALF_EVEN, ROUND_HALF_UP, Decimal
from typing import TYPE_CHECKING, Any, Final

import pandas as pd

from arpi.constants import (
    CHECK_CATEGORY_BUSINESS_RULE,
    CHECK_CATEGORY_COMPLETENESS,
    CHECK_CATEGORY_PRIVACY,
    CHECK_CATEGORY_REFERENTIAL,
    CHECK_CATEGORY_STRUCTURAL,
    CHECK_CATEGORY_UNIQUENESS,
    SOURCE_SYSTEM,
    TARGET_DEPARTMENT_METRIC,
    TARGET_METRIC_KPI_IDS,
    TARGET_SCOPE_DEPARTMENT,
    TARGET_SCOPE_EMPLOYEE,
    TARGET_SCOPE_METRICS,
    TARGET_SCOPE_STORE,
    TARGET_SCOPE_TYPES,
)
from arpi.exceptions import GenerationError
from arpi.generation.base import BaseGenerator, GeneratedDataset
from arpi.generation.calendar import build_calendar_rows
from arpi.generation.dealership import STORE_DEFINITIONS
from arpi.utilities.dates import date_key
from arpi.utilities.seeding import rng_for
from arpi.validation.checks import (
    check_column_schema,
    check_no_prohibited_pii_columns,
)
from arpi.validation.registry import CheckDefinition, CheckLayer, register_checks
from arpi.validation.results import CheckResult, CheckSeverity, ValidationReport

if TYPE_CHECKING:  # pragma: no cover - import cycle guard for type checking only
    from arpi.config import ArpiConfig

__all__ = [
    "ENTITY_SALES_TARGET",
    "SALES_TARGET_COLUMNS",
    "SALES_TARGET_DTYPES",
    "SALES_TARGET_GRAIN_COLUMNS",
    "SALES_TARGET_NAMESPACE",
    "STORE_PLANNING_BASELINE",
    "STRETCH_TARGET_MULTIPLIER",
    "TARGET_MONTH_SEASONALITY",
    "TARGET_PLANNING_VARIATION",
    "generate_sales_target_dataset",
    "validate_sales_target_dataset",
]

# ---------------------------------------------------------------------------------------
# Entity contract
# ---------------------------------------------------------------------------------------
#: Logical entity name, as the loader's ingestion spec looks it up.
ENTITY_SALES_TARGET: Final = "sales_target"

#: Stable seeding namespace. Never renamed: renaming it would change every drawn value.
SALES_TARGET_NAMESPACE: Final = "sales_target"

#: The generated column contract: exact names, exact order.
SALES_TARGET_COLUMNS: Final[tuple[str, ...]] = (
    "sales_target_id",
    "target_month_date_key",
    "dealership_id",
    "target_scope_type",
    "target_scope_id",
    "department_name",
    "employee_id",
    "kpi_id",
    "target_value",
    "stretch_target_value",
    "source_system",
)

#: ``object`` for the two money columns so pandas never coerces a ``Decimal`` to float.
SALES_TARGET_DTYPES: Final[dict[str, str]] = {
    "sales_target_id": "string",
    "target_month_date_key": "int32",
    "dealership_id": "string",
    "target_scope_type": "string",
    "target_scope_id": "string",
    "department_name": "string",
    "employee_id": "string",
    "kpi_id": "string",
    "target_value": "object",
    "stretch_target_value": "object",
    "source_system": "string",
}

#: The declared grain, enforced physically by ``uq_fact_sales_target_grain``.
SALES_TARGET_GRAIN_COLUMNS: Final[tuple[str, ...]] = (
    "dealership_id",
    "target_month_date_key",
    "kpi_id",
    "target_scope_type",
    "target_scope_id",
)

#: The two columns that are nullable by contract: they are populated only by the scope
#: type that owns them.
SALES_TARGET_NULLABLE_COLUMNS: Final[tuple[str, ...]] = ("department_name", "employee_id")

#: Cent precision, applied exactly once per emitted value.
_CENTS: Final = Decimal("0.01")

#: The most decimal places a governed target value may carry. numeric(14,2) on the fact.
_MAX_SCALE: Final = 2

#: Whole units, for the unit-target quantization step that precedes it.
_WHOLE: Final = Decimal("1")


# ---------------------------------------------------------------------------------------
# Planning parameters -- PROJECT DEFAULTS FOR A FICTIONAL GROUP
# ---------------------------------------------------------------------------------------
# Every number below is a parameter of a synthetic operating plan for Granite Auto Group.
# None of them is an industry benchmark, a manufacturer objective or a market standard,
# and no reader may treat any of them as one. They are declared here, beside the
# generator that consumes them, for the same reason PACK_AMOUNT_BY_STORE lives beside the
# sale generator: this is the repository's synthetic-generation configuration convention.
# They are deliberately NOT in config/reference/, which ADR-0011 reserves for the
# sanitized public listing lane.
@dataclass(frozen=True, slots=True)
class StorePlanningBaseline:
    """One store's exogenous planning assumptions.

    Attributes:
        units_per_selling_day: Planned retail deliveries per governed selling day. The
            store's planning scale, set from its operating model and floor capacity.
        planned_total_gross_per_unit: Planned total gross per retail unit, in dollars.
        planned_front_gross_share: The share of planned total gross the Sales department
            is expected to produce. The Finance department carries the remainder
            exactly, so the two department targets sum to the store target.
    """

    units_per_selling_day: float
    planned_total_gross_per_unit: Decimal
    planned_front_gross_share: Decimal


#: The three stores' planning baselines.
#:
#: GSA-001 is the volume Chevrolet franchise, GSA-002 the all-weather Subaru franchise
#: with a thinner front end and a steady F&I contribution, GSA-003 an independent
#: pre-owned centre that sells fewer units at a wider front margin and has no captive
#: F&I relationship. The three are deliberately unlike one another: a plan that treated
#: an independent used operation as a small franchise store would be a modelling error
#: the console would then present as a finding.
STORE_PLANNING_BASELINE: Final[dict[str, StorePlanningBaseline]] = {
    "GSA-001": StorePlanningBaseline(
        units_per_selling_day=1.30,
        planned_total_gross_per_unit=Decimal("3800.00"),
        planned_front_gross_share=Decimal("0.64"),
    ),
    "GSA-002": StorePlanningBaseline(
        units_per_selling_day=1.18,
        planned_total_gross_per_unit=Decimal("2850.00"),
        planned_front_gross_share=Decimal("0.60"),
    ),
    "GSA-003": StorePlanningBaseline(
        units_per_selling_day=0.72,
        planned_total_gross_per_unit=Decimal("4050.00"),
        planned_front_gross_share=Decimal("0.74"),
    ),
}

#: Planning seasonality: the month-of-year shape a dealer group writes its plan against.
#:
#: Deliberately a SMOOTHER shape than the realized seasonality
#: ``arpi.generation.sale.SALE_MONTH_WEIGHT`` encodes. A plan written before the month
#: starts cannot know the month's actual shape, and copying the realized weights would
#: be a subtler form of the outcome leakage this module exists to avoid: every month
#: would then attain almost identically and the console could never show a store ahead
#: of plan in one month and behind in the next.
TARGET_MONTH_SEASONALITY: Final[dict[int, float]] = {
    1: 0.88,
    2: 0.92,
    3: 1.08,
    4: 1.10,
    5: 1.12,
    6: 1.08,
    7: 1.05,
    8: 1.08,
    9: 1.02,
    10: 0.97,
    11: 0.95,
    12: 1.05,
}

#: Half-width of the seeded planning variation applied to a store-month unit target.
#:
#: A real plan is not a formula: it carries the desk's judgement about a model launch,
#: a staffing change or a marketing push. This is that judgement, modelled as bounded
#: seeded noise so the committed dataset shows a plausible spread rather than a smooth
#: curve. It is drawn from the ARPI master seed, so it is reproducible.
TARGET_PLANNING_VARIATION: Final = 0.055

#: Half-width of the seeded planning variation applied to planned gross per unit.
TARGET_GROSS_VARIATION: Final = 0.060

#: The stretch goal, as a multiple of the committed target. A project default.
STRETCH_TARGET_MULTIPLIER: Final = Decimal("1.08")


# ---------------------------------------------------------------------------------------
# Data-quality identifiers
# ---------------------------------------------------------------------------------------
CHECK_TARGET_UNIQUE_GRAIN: Final = "DQ-TGT-001"
CHECK_TARGET_SCHEMA_MATCHES: Final = "DQ-TGT-002"
CHECK_TARGET_MONTH_KEY_FIRST_OF_MONTH: Final = "DQ-TGT-003"
CHECK_TARGET_MONTH_IN_WINDOW: Final = "DQ-TGT-004"
CHECK_TARGET_SCOPE_TYPE_VALID: Final = "DQ-TGT-005"
CHECK_TARGET_SCOPE_IDENTITY: Final = "DQ-TGT-006"
CHECK_TARGET_KPI_VOCABULARY: Final = "DQ-TGT-007"
CHECK_TARGET_DEALERSHIP_RESOLVES: Final = "DQ-TGT-008"
CHECK_TARGET_VALUE_NONNEGATIVE: Final = "DQ-TGT-009"
CHECK_TARGET_STRETCH_NOT_BELOW_TARGET: Final = "DQ-TGT-010"
CHECK_TARGET_EXACT_PRECISION: Final = "DQ-TGT-011"
CHECK_TARGET_DEPARTMENT_SPLIT_SUMS: Final = "DQ-TGT-012"
CHECK_TARGET_SOURCE_SYSTEM: Final = "DQ-TGT-013"
CHECK_TARGET_NO_PROHIBITED_PII: Final = "DQ-TGT-014"

register_checks(
    (
        CheckDefinition(
            check_id=CHECK_TARGET_UNIQUE_GRAIN,
            check_name="fact_sales_target is unique on its declared grain",
            category=CHECK_CATEGORY_UNIQUENESS,
            severity=CheckSeverity.CRITICAL,
            layer=CheckLayer.PYTHON,
            entity=ENTITY_SALES_TARGET,
            description=(
                "Two rows at one (store, month, KPI, scope) would double the denominator "
                "of every attainment figure and halve the apparent attainment."
            ),
            applies_to=("warehouse.fact_sales_target",),
        ),
        CheckDefinition(
            check_id=CHECK_TARGET_SCHEMA_MATCHES,
            check_name="sales target matches its declared column contract",
            category=CHECK_CATEGORY_STRUCTURAL,
            severity=CheckSeverity.CRITICAL,
            layer=CheckLayer.PYTHON,
            entity=ENTITY_SALES_TARGET,
            description="A column added or reordered silently breaks the raw COPY column list.",
            applies_to=("warehouse.fact_sales_target",),
        ),
        CheckDefinition(
            check_id=CHECK_TARGET_MONTH_KEY_FIRST_OF_MONTH,
            check_name="fact_sales_target.target_month_date_key is a first-of-month key",
            category=CHECK_CATEGORY_BUSINESS_RULE,
            severity=CheckSeverity.CRITICAL,
            layer=CheckLayer.PYTHON,
            entity=ENTITY_SALES_TARGET,
            description=(
                "A target month keyed to a mid-month date would make the plan and the "
                "actual disagree about what a month is."
            ),
            applies_to=("warehouse.fact_sales_target",),
        ),
        CheckDefinition(
            check_id=CHECK_TARGET_MONTH_IN_WINDOW,
            check_name="fact_sales_target months lie inside the reporting window",
            category=CHECK_CATEGORY_REFERENTIAL,
            severity=CheckSeverity.CRITICAL,
            layer=CheckLayer.PYTHON,
            entity=ENTITY_SALES_TARGET,
            description=(
                "A target for a month the calendar does not contain has no selling-day "
                "denominator and no actual to attain against."
            ),
            applies_to=("warehouse.fact_sales_target", "warehouse.dim_date"),
        ),
        CheckDefinition(
            check_id=CHECK_TARGET_SCOPE_TYPE_VALID,
            check_name="fact_sales_target.target_scope_type is in its governed vocabulary",
            category=CHECK_CATEGORY_BUSINESS_RULE,
            severity=CheckSeverity.CRITICAL,
            layer=CheckLayer.PYTHON,
            entity=ENTITY_SALES_TARGET,
            description=(
                "An unknown scope type cannot be excluded from a store total, so it would "
                "silently inflate one."
            ),
            applies_to=("warehouse.fact_sales_target",),
        ),
        CheckDefinition(
            check_id=CHECK_TARGET_SCOPE_IDENTITY,
            check_name="fact_sales_target scope identity matches its scope type",
            category=CHECK_CATEGORY_COMPLETENESS,
            severity=CheckSeverity.CRITICAL,
            layer=CheckLayer.PYTHON,
            entity=ENTITY_SALES_TARGET,
            description=(
                "Store scope must name its own store, Department scope must carry the "
                "department and no employee, Employee scope must carry the employee and "
                "no department. An ambiguous combination has no attribution rule."
            ),
            applies_to=("warehouse.fact_sales_target",),
        ),
        CheckDefinition(
            check_id=CHECK_TARGET_KPI_VOCABULARY,
            check_name="fact_sales_target.kpi_id names a supported target metric",
            category=CHECK_CATEGORY_BUSINESS_RULE,
            severity=CheckSeverity.CRITICAL,
            layer=CheckLayer.PYTHON,
            entity=ENTITY_SALES_TARGET,
            description=(
                "The targeted metric decides which actual is the numerator. An "
                "unsupported id would produce a target with no comparable actual."
            ),
            applies_to=("warehouse.fact_sales_target",),
        ),
        CheckDefinition(
            check_id=CHECK_TARGET_DEALERSHIP_RESOLVES,
            check_name="fact_sales_target.dealership_id resolves to a governed store",
            category=CHECK_CATEGORY_REFERENTIAL,
            severity=CheckSeverity.CRITICAL,
            layer=CheckLayer.PYTHON,
            entity=ENTITY_SALES_TARGET,
            description="A target for a store that does not exist can never be attained.",
            applies_to=("warehouse.fact_sales_target", "warehouse.dim_dealership"),
        ),
        CheckDefinition(
            check_id=CHECK_TARGET_VALUE_NONNEGATIVE,
            check_name="fact_sales_target.target_value is never negative",
            category=CHECK_CATEGORY_BUSINESS_RULE,
            severity=CheckSeverity.CRITICAL,
            layer=CheckLayer.PYTHON,
            entity=ENTITY_SALES_TARGET,
            description="A negative goal is not a goal; it would invert every attainment ratio.",
            applies_to=("warehouse.fact_sales_target",),
        ),
        CheckDefinition(
            check_id=CHECK_TARGET_STRETCH_NOT_BELOW_TARGET,
            check_name="fact_sales_target.stretch_target_value is never below target_value",
            category=CHECK_CATEGORY_BUSINESS_RULE,
            severity=CheckSeverity.CRITICAL,
            layer=CheckLayer.PYTHON,
            entity=ENTITY_SALES_TARGET,
            description="A stretch goal beneath the committed goal is not a stretch goal.",
            applies_to=("warehouse.fact_sales_target",),
        ),
        CheckDefinition(
            check_id=CHECK_TARGET_EXACT_PRECISION,
            check_name="fact_sales_target values are exact to two decimal places",
            category=CHECK_CATEGORY_BUSINESS_RULE,
            severity=CheckSeverity.CRITICAL,
            layer=CheckLayer.PYTHON,
            entity=ENTITY_SALES_TARGET,
            description=(
                "A binary float in a target would make the attainment denominator "
                "irreproducible and the reconciliation identity fail in the last place."
            ),
            applies_to=("warehouse.fact_sales_target",),
        ),
        CheckDefinition(
            check_id=CHECK_TARGET_DEPARTMENT_SPLIT_SUMS,
            check_name="department gross targets sum exactly to the store total-gross target",
            category=CHECK_CATEGORY_BUSINESS_RULE,
            severity=CheckSeverity.CRITICAL,
            layer=CheckLayer.PYTHON,
            entity=ENTITY_SALES_TARGET,
            description=(
                "The Sales and Finance department targets are a partition of the store's "
                "total-gross target, mirroring front + back = total on the sale fact. If "
                "they did not sum, a department view and a store view would disagree."
            ),
            applies_to=("warehouse.fact_sales_target",),
        ),
        CheckDefinition(
            check_id=CHECK_TARGET_SOURCE_SYSTEM,
            check_name="fact_sales_target.source_system is the synthetic generator",
            category=CHECK_CATEGORY_BUSINESS_RULE,
            severity=CheckSeverity.CRITICAL,
            layer=CheckLayer.PYTHON,
            entity=ENTITY_SALES_TARGET,
            description=(
                "The lineage marker is what stops a reader mistaking a synthetic "
                "operating goal for a real dealership plan."
            ),
            applies_to=("warehouse.fact_sales_target",),
        ),
        CheckDefinition(
            check_id=CHECK_TARGET_NO_PROHIBITED_PII,
            check_name="sales target declares no prohibited personal-data column",
            category=CHECK_CATEGORY_PRIVACY,
            severity=CheckSeverity.CRITICAL,
            layer=CheckLayer.PYTHON,
            entity=ENTITY_SALES_TARGET,
            description=(
                "Targets are non-personal. An employee-scope row carries a synthetic "
                "identifier and never a name, a pay plan or a contact detail."
            ),
            applies_to=("warehouse.fact_sales_target",),
        ),
    )
)


# ---------------------------------------------------------------------------------------
# Generation
# ---------------------------------------------------------------------------------------
@dataclass(frozen=True, slots=True)
class PlannedMonth:
    """One store-month's planning frame, before any target row is emitted.

    Attributes:
        dealership_id: The store the plan belongs to.
        month_start: First day of the planned month.
        selling_days: Governed selling days in the month, from ``dim_date``.
    """

    dealership_id: str
    month_start: date
    selling_days: int


def _planning_frame(config: ArpiConfig) -> tuple[PlannedMonth, ...]:
    """Build the exogenous planning frame: every store-month, with its selling days.

    The selling-day count is rebuilt from :func:`build_calendar_rows`, which is the one
    implementation of the ADR-0002 selling-day rule. No second calendar is defined here.

    Args:
        config: Resolved configuration supplying the reporting window.

    Returns:
        One :class:`PlannedMonth` per active store per month in the window, ordered by
        store then month.
    """
    calendar = build_calendar_rows(config.reporting.start_date, config.reporting.end_date)
    selling_days_by_month: dict[date, int] = {}
    for month_start, is_selling_day in zip(
        calendar["month_start_date"], calendar["is_selling_day"], strict=True
    ):
        key = month_start.date() if isinstance(month_start, pd.Timestamp) else month_start
        selling_days_by_month[key] = selling_days_by_month.get(key, 0) + int(bool(is_selling_day))

    months = sorted(selling_days_by_month)
    stores = sorted(
        (store for store in STORE_DEFINITIONS if store.is_active),
        key=lambda store: store.dealership_id,
    )
    return tuple(
        PlannedMonth(
            dealership_id=store.dealership_id,
            month_start=month,
            selling_days=selling_days_by_month[month],
        )
        for store in stores
        for month in months
    )


def _variation(rng: random.Random, half_width: float) -> Decimal:
    """Draw one bounded planning variation as an exact multiplier.

    Args:
        rng: The entity's dedicated generator.
        half_width: Half-width of the uniform draw, as a fraction of 1.

    Returns:
        ``1 + u`` where ``u`` is uniform on ``[-half_width, +half_width]``, quantized to
        six places so the multiplier itself is exact before it touches money.
    """
    drawn = rng.uniform(-half_width, half_width)
    return (Decimal(1) + Decimal(repr(drawn))).quantize(
        Decimal("0.000001"), rounding=ROUND_HALF_EVEN
    )


def _whole_units(value: Decimal) -> Decimal:
    """Quantize a planned unit count to whole units, carried at cent scale.

    Units are whole: a store does not commit to 57.4 deliveries. The value is
    nevertheless carried in ``numeric(14,2)`` alongside currency targets, so it is
    rendered as ``57.00`` rather than ``57``.

    Args:
        value: The unrounded planned unit count.

    Returns:
        The value rounded half-up to a whole number and restated at cent scale.
    """
    return value.quantize(_WHOLE, rounding=ROUND_HALF_UP).quantize(_CENTS)


def _money(value: Decimal) -> Decimal:
    """Quantize a planned money value to the cent, half-up."""
    return value.quantize(_CENTS, rounding=ROUND_HALF_UP)


class SalesTargetGenerator(BaseGenerator):
    """Build the monthly operating plan for every store in the reporting window."""

    entity_name = ENTITY_SALES_TARGET
    declared_columns = SALES_TARGET_COLUMNS
    namespace = SALES_TARGET_NAMESPACE

    def build_frame(self, config: ArpiConfig) -> pd.DataFrame:
        """Build the sales-target frame.

        Args:
            config: Resolved configuration supplying the master seed and the window.

        Returns:
            A frame with the eleven contract columns, in order, ordered by store, month,
            scope type, scope id and KPI so the output is byte-stable.

        Raises:
            GenerationError: If a store in the window has no planning baseline. A store
                with no plan would silently produce no targets, which is
                indistinguishable from a store that missed its plan.
        """
        rng = rng_for(config.random_seed, SALES_TARGET_NAMESPACE)
        records: list[dict[str, Any]] = []

        for planned in _planning_frame(config):
            baseline = STORE_PLANNING_BASELINE.get(planned.dealership_id)
            if baseline is None:
                raise GenerationError(
                    f"Store {planned.dealership_id!r} has no entry in "
                    "arpi.generation.sales_target.STORE_PLANNING_BASELINE, so no "
                    "operating plan can be written for it. Add the store's planning "
                    "baseline rather than letting it generate no targets.",
                    entity=ENTITY_SALES_TARGET,
                    dealership_id=planned.dealership_id,
                )
            records.extend(_store_month_rows(rng, planned, baseline))

        frame = pd.DataFrame.from_records(records, columns=list(SALES_TARGET_COLUMNS))
        frame = frame.sort_values(
            by=[
                "dealership_id",
                "target_month_date_key",
                "target_scope_type",
                "target_scope_id",
                "kpi_id",
            ],
            kind="stable",
            ignore_index=True,
        )
        frame["sales_target_id"] = [f"TGT-{ordinal:08d}" for ordinal in range(1, len(frame) + 1)]
        return frame.astype(SALES_TARGET_DTYPES)


def _store_month_rows(
    rng: random.Random,
    planned: PlannedMonth,
    baseline: StorePlanningBaseline,
) -> list[dict[str, Any]]:
    """Emit every target row for one store-month.

    Four rows: the store's unit target and total-gross target, and the two department
    gross targets that partition the store's total-gross target exactly.

    Args:
        rng: The entity's dedicated generator. Consumed in a fixed order, so the output
            is stable for a given seed.
        planned: The store-month planning frame.
        baseline: The store's exogenous planning assumptions.

    Returns:
        Four record dictionaries, without ``sales_target_id`` (assigned after sorting).
    """
    month_key = date_key(planned.month_start)
    unit_variation = _variation(rng, TARGET_PLANNING_VARIATION)
    gross_variation = _variation(rng, TARGET_GROSS_VARIATION)

    seasonality = Decimal(repr(TARGET_MONTH_SEASONALITY[planned.month_start.month]))
    per_day = Decimal(repr(baseline.units_per_selling_day))
    unit_target = _whole_units(
        per_day * Decimal(planned.selling_days) * seasonality * unit_variation
    )

    gross_target = _money(unit_target * baseline.planned_total_gross_per_unit * gross_variation)
    # The Sales department's share is struck first and Finance carries the remainder, so
    # the two department targets sum to the store target to the cent by construction
    # rather than by a rounding coincidence.
    front_target = _money(gross_target * baseline.planned_front_gross_share)
    back_target = gross_target - front_target

    rows = [
        _row(
            planned,
            month_key,
            scope_type=TARGET_SCOPE_STORE,
            scope_id=planned.dealership_id,
            department_name=None,
            kpi_id="KPI-SLS-001",
            target_value=unit_target,
            stretch_value=_whole_units(unit_target * STRETCH_TARGET_MULTIPLIER),
        ),
        _row(
            planned,
            month_key,
            scope_type=TARGET_SCOPE_STORE,
            scope_id=planned.dealership_id,
            department_name=None,
            kpi_id="KPI-GRS-003",
            target_value=gross_target,
            stretch_value=_money(gross_target * STRETCH_TARGET_MULTIPLIER),
        ),
    ]
    for department, (kpi_id, value) in (
        ("Sales", (TARGET_DEPARTMENT_METRIC["Sales"], front_target)),
        ("Finance", (TARGET_DEPARTMENT_METRIC["Finance"], back_target)),
    ):
        rows.append(
            _row(
                planned,
                month_key,
                scope_type=TARGET_SCOPE_DEPARTMENT,
                scope_id=department,
                department_name=department,
                kpi_id=kpi_id,
                target_value=value,
                stretch_value=_money(value * STRETCH_TARGET_MULTIPLIER),
            )
        )
    return rows


def _row(
    planned: PlannedMonth,
    month_key: int,
    *,
    scope_type: str,
    scope_id: str,
    department_name: str | None,
    kpi_id: str,
    target_value: Decimal,
    stretch_value: Decimal,
) -> dict[str, Any]:
    """Assemble one target record."""
    return {
        "sales_target_id": None,
        "target_month_date_key": month_key,
        "dealership_id": planned.dealership_id,
        "target_scope_type": scope_type,
        "target_scope_id": scope_id,
        "department_name": department_name,
        # DASH.5 generates no employee-scope target. The column exists because the
        # scope vocabulary is permanent; see the module docstring.
        "employee_id": None,
        "kpi_id": kpi_id,
        "target_value": target_value,
        "stretch_target_value": stretch_value,
        "source_system": SOURCE_SYSTEM,
    }


def generate_sales_target_dataset(config: ArpiConfig) -> GeneratedDataset:
    """Generate the ``sales_target`` dataset feeding ``warehouse.fact_sales_target``.

    Args:
        config: Resolved configuration.

    Returns:
        The generated dataset, schema-checked against the column contract.
    """
    return SalesTargetGenerator().generate(config)


# ---------------------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------------------
def validate_sales_target_dataset(
    dataset: GeneratedDataset, config: ArpiConfig
) -> ValidationReport:
    """Run ``DQ-TGT-001`` through ``DQ-TGT-014`` against the generated plan.

    Args:
        dataset: The generated ``sales_target`` dataset.
        config: Resolved configuration, used to bound the target months.

    Returns:
        A report containing fourteen results, in check-id order.
    """
    frame = dataset.frame
    return ValidationReport(
        (
            _check_grain(frame),
            check_column_schema(
                frame,
                SALES_TARGET_COLUMNS,
                check_id=CHECK_TARGET_SCHEMA_MATCHES,
                check_name="sales target matches its declared column contract",
                target_object=ENTITY_SALES_TARGET,
            ),
            _check_month_key_is_first_of_month(frame),
            _check_month_in_window(frame, config),
            _check_scope_type_valid(frame),
            _check_scope_identity(frame),
            _check_kpi_vocabulary(frame),
            _check_dealership_resolves(frame),
            _check_target_nonnegative(frame),
            _check_stretch_not_below_target(frame),
            _check_exact_precision(frame),
            _check_department_split_sums(frame),
            _check_source_system(frame),
            check_no_prohibited_pii_columns(
                frame,
                check_id=CHECK_TARGET_NO_PROHIBITED_PII,
                check_name="sales target declares no prohibited personal-data column",
                target_object=ENTITY_SALES_TARGET,
            ),
        )
    )


def _target_result(check_id: str, check_name: str, category: str) -> CheckResult:
    """Build the passing skeleton shared by the target checks."""
    return CheckResult(
        check_id=check_id,
        check_name=check_name,
        target_object=ENTITY_SALES_TARGET,
        severity=CheckSeverity.CRITICAL,
        check_category=category,
        expected_value=0.0,
        observed_value=0.0,
    )


def _check_grain(frame: pd.DataFrame) -> CheckResult:
    """``DQ-TGT-001`` -- the declared grain is unique."""
    base = CheckResult(
        check_id=CHECK_TARGET_UNIQUE_GRAIN,
        check_name="fact_sales_target is unique on its declared grain",
        target_object=ENTITY_SALES_TARGET,
        severity=CheckSeverity.CRITICAL,
        check_category=CHECK_CATEGORY_UNIQUENESS,
        expected_value=float(frame.shape[0]),
        observed_value=float(frame.shape[0]),
    )
    duplicated = int(frame.duplicated(subset=list(SALES_TARGET_GRAIN_COLUMNS)).sum())
    if duplicated == 0:
        return base
    return base.failed(
        f"{duplicated} row(s) repeat the grain "
        f"({', '.join(SALES_TARGET_GRAIN_COLUMNS)}), which doubles an attainment "
        "denominator.",
        observed_value=float(frame.shape[0] - duplicated),
        failed_record_count=duplicated,
    )


def _check_month_key_is_first_of_month(frame: pd.DataFrame) -> CheckResult:
    """``DQ-TGT-003`` -- every ``target_month_date_key`` ends in ``01``."""
    base = _target_result(
        CHECK_TARGET_MONTH_KEY_FIRST_OF_MONTH,
        "fact_sales_target.target_month_date_key is a first-of-month key",
        CHECK_CATEGORY_BUSINESS_RULE,
    )
    offending = int((frame["target_month_date_key"] % 100 != 1).sum())
    if offending == 0:
        return base
    return base.failed(
        f"{offending} target month key(s) do not address the first day of a month.",
        observed_value=float(offending),
        failed_record_count=offending,
    )


def _check_month_in_window(frame: pd.DataFrame, config: ArpiConfig) -> CheckResult:
    """``DQ-TGT-004`` -- every target month lies inside the reporting window."""
    base = _target_result(
        CHECK_TARGET_MONTH_IN_WINDOW,
        "fact_sales_target months lie inside the reporting window",
        CHECK_CATEGORY_REFERENTIAL,
    )
    first = date_key(config.reporting.start_date.replace(day=1))
    last = date_key(config.reporting.end_date.replace(day=1))
    keys = frame["target_month_date_key"]
    offending = int(((keys < first) | (keys > last)).sum())
    if offending == 0:
        return base
    return base.failed(
        f"{offending} target(s) fall outside the reporting window "
        f"({first}..{last}); they would have no selling-day denominator.",
        observed_value=float(offending),
        failed_record_count=offending,
    )


def _check_scope_type_valid(frame: pd.DataFrame) -> CheckResult:
    """``DQ-TGT-005`` -- every scope type is in the governed vocabulary."""
    base = _target_result(
        CHECK_TARGET_SCOPE_TYPE_VALID,
        "fact_sales_target.target_scope_type is in its governed vocabulary",
        CHECK_CATEGORY_BUSINESS_RULE,
    )
    unknown = sorted(
        {str(value) for value in frame["target_scope_type"] if str(value) not in TARGET_SCOPE_TYPES}
    )
    if not unknown:
        return base
    return base.failed(
        f"Unknown target scope type(s): {', '.join(unknown)}.",
        observed_value=float(len(unknown)),
        failed_record_count=len(unknown),
    )


def _check_scope_identity(frame: pd.DataFrame) -> CheckResult:
    """``DQ-TGT-006`` -- the scope identity columns agree with the scope type."""
    base = _target_result(
        CHECK_TARGET_SCOPE_IDENTITY,
        "fact_sales_target scope identity matches its scope type",
        CHECK_CATEGORY_COMPLETENESS,
    )
    problems = 0
    for row in frame.itertuples(index=False):
        scope_type = str(row.target_scope_type)
        scope_id = row.target_scope_id
        department = row.department_name
        employee = row.employee_id
        blank_scope_id = scope_id is None or pd.isna(scope_id) or str(scope_id).strip() == ""
        has_department = department is not None and not pd.isna(department)
        has_employee = employee is not None and not pd.isna(employee)
        if blank_scope_id:
            problems += 1
            continue
        contradictions = {
            TARGET_SCOPE_STORE: has_department
            or has_employee
            or str(scope_id) != str(row.dealership_id),
            TARGET_SCOPE_DEPARTMENT: not has_department
            or has_employee
            or str(department) != str(scope_id),
            TARGET_SCOPE_EMPLOYEE: has_department
            or not has_employee
            or str(employee) != str(scope_id),
        }
        if contradictions.get(scope_type, True):
            problems += 1
    if problems == 0:
        return base
    return base.failed(
        f"{problems} row(s) carry a scope identity that contradicts their scope type.",
        observed_value=float(problems),
        failed_record_count=problems,
    )


def _check_kpi_vocabulary(frame: pd.DataFrame) -> CheckResult:
    """``DQ-TGT-007`` -- the targeted metric is one the domain supports for its scope."""
    base = _target_result(
        CHECK_TARGET_KPI_VOCABULARY,
        "fact_sales_target.kpi_id names a supported target metric",
        CHECK_CATEGORY_BUSINESS_RULE,
    )
    problems = 0
    for row in frame.itertuples(index=False):
        kpi_id = str(row.kpi_id)
        scope_type = str(row.target_scope_type)
        if kpi_id not in TARGET_METRIC_KPI_IDS:
            problems += 1
            continue
        allowed = TARGET_SCOPE_METRICS.get(scope_type, ())
        if kpi_id not in allowed:
            problems += 1
    if problems == 0:
        return base
    return base.failed(
        f"{problems} row(s) target a metric their scope does not own; the supported "
        f"vocabulary is {TARGET_SCOPE_METRICS}.",
        observed_value=float(problems),
        failed_record_count=problems,
    )


def _check_dealership_resolves(frame: pd.DataFrame) -> CheckResult:
    """``DQ-TGT-008`` -- every ``dealership_id`` names a governed store."""
    base = _target_result(
        CHECK_TARGET_DEALERSHIP_RESOLVES,
        "fact_sales_target.dealership_id resolves to a governed store",
        CHECK_CATEGORY_REFERENTIAL,
    )
    known = {store.dealership_id for store in STORE_DEFINITIONS}
    unknown = sorted({str(value) for value in frame["dealership_id"] if str(value) not in known})
    if not unknown:
        return base
    return base.failed(
        f"Target(s) reference store(s) that do not exist: {', '.join(unknown)}.",
        observed_value=float(len(unknown)),
        failed_record_count=len(unknown),
    )


def _check_target_nonnegative(frame: pd.DataFrame) -> CheckResult:
    """``DQ-TGT-009`` -- no target or stretch target is negative."""
    base = _target_result(
        CHECK_TARGET_VALUE_NONNEGATIVE,
        "fact_sales_target.target_value is never negative",
        CHECK_CATEGORY_BUSINESS_RULE,
    )
    offending = sum(
        1
        for target, stretch in zip(
            frame["target_value"], frame["stretch_target_value"], strict=True
        )
        if Decimal(str(target)) < 0 or Decimal(str(stretch)) < 0
    )
    if offending == 0:
        return base
    return base.failed(
        f"{offending} row(s) carry a negative goal.",
        observed_value=float(offending),
        failed_record_count=offending,
    )


def _check_stretch_not_below_target(frame: pd.DataFrame) -> CheckResult:
    """``DQ-TGT-010`` -- the stretch goal is never beneath the committed goal."""
    base = _target_result(
        CHECK_TARGET_STRETCH_NOT_BELOW_TARGET,
        "fact_sales_target.stretch_target_value is never below target_value",
        CHECK_CATEGORY_BUSINESS_RULE,
    )
    offending = sum(
        1
        for target, stretch in zip(
            frame["target_value"], frame["stretch_target_value"], strict=True
        )
        if Decimal(str(stretch)) < Decimal(str(target))
    )
    if offending == 0:
        return base
    return base.failed(
        f"{offending} row(s) carry a stretch goal beneath the committed goal.",
        observed_value=float(offending),
        failed_record_count=offending,
    )


def _check_exact_precision(frame: pd.DataFrame) -> CheckResult:
    """``DQ-TGT-011`` -- every value is a ``Decimal`` with at most two decimal places."""
    base = _target_result(
        CHECK_TARGET_EXACT_PRECISION,
        "fact_sales_target values are exact to two decimal places",
        CHECK_CATEGORY_BUSINESS_RULE,
    )
    offending = 0
    for column in ("target_value", "stretch_target_value"):
        for value in frame[column]:
            if not isinstance(value, Decimal):
                offending += 1
                continue
            exponent = value.as_tuple().exponent
            # A non-integer exponent means NaN or Infinity, which is not a target either.
            if not isinstance(exponent, int) or -exponent > _MAX_SCALE:
                offending += 1
    if offending == 0:
        return base
    return base.failed(
        f"{offending} value(s) are not exact Decimals quantized to the cent. A binary "
        "float in a target makes its attainment denominator irreproducible.",
        observed_value=float(offending),
        failed_record_count=offending,
    )


def _check_department_split_sums(frame: pd.DataFrame) -> CheckResult:
    """``DQ-TGT-012`` -- department gross targets partition the store gross target."""
    base = _target_result(
        CHECK_TARGET_DEPARTMENT_SPLIT_SUMS,
        "department gross targets sum exactly to the store total-gross target",
        CHECK_CATEGORY_BUSINESS_RULE,
    )
    store_gross: dict[tuple[str, str], Decimal] = {}
    department_gross: dict[tuple[str, str], Decimal] = {}
    for row in frame.itertuples(index=False):
        key = (str(row.dealership_id), str(row.target_month_date_key))
        value = Decimal(str(row.target_value))
        if str(row.target_scope_type) == TARGET_SCOPE_STORE and str(row.kpi_id) == "KPI-GRS-003":
            store_gross[key] = store_gross.get(key, Decimal(0)) + value
        elif str(row.target_scope_type) == TARGET_SCOPE_DEPARTMENT:
            department_gross[key] = department_gross.get(key, Decimal(0)) + value

    mismatched = sorted(
        f"{store}/{month}"
        for (store, month), total in store_gross.items()
        if department_gross.get((store, month), Decimal(0)) != total
    )
    if not mismatched:
        return base
    return base.failed(
        f"{len(mismatched)} store-month(s) whose department gross targets do not sum to "
        f"the store total-gross target: {', '.join(mismatched[:5])}.",
        observed_value=float(len(mismatched)),
        failed_record_count=len(mismatched),
    )


def _check_source_system(frame: pd.DataFrame) -> CheckResult:
    """``DQ-TGT-013`` -- the lineage marker is the synthetic generator, on every row."""
    base = _target_result(
        CHECK_TARGET_SOURCE_SYSTEM,
        "fact_sales_target.source_system is the synthetic generator",
        CHECK_CATEGORY_BUSINESS_RULE,
    )
    offending = int((frame["source_system"] != SOURCE_SYSTEM).sum())
    if offending == 0:
        return base
    return base.failed(
        f"{offending} row(s) do not carry source_system = {SOURCE_SYSTEM!r}.",
        observed_value=float(offending),
        failed_record_count=offending,
    )
