/**
 * ARPI — Railway project definition, as code.
 *
 * WHAT THIS FILE IS
 * -----------------
 * Railway's Infrastructure as Code entry point. `railway config plan` previews
 * the difference between this file and the live project without changing
 * anything; `railway config apply` converges the project onto it. Both are
 * provided by the Railway CLI, and the convergence is Railway's own: its
 * `ensureGraphResources` creates a service only when no service of that name
 * exists, and creates a database's volume only when that database has none. That
 * is where this deployment's idempotency actually comes from — it is a property
 * of the platform's apply path, not of a loop in a script of ours.
 *
 * WHY THIS FILE EXISTS AT ALL, GIVEN `railway.json`
 * ------------------------------------------------
 * `railway.json` cannot create a service, create a database, create a domain, or
 * set a single variable. Config as Code has no vocabulary for any of those. So
 * `railway.json` remains the human-authored, reviewable statement of the BUILD
 * and DEPLOY configuration — and this file IMPORTS it rather than restating it,
 * so the two can never drift — while everything Config as Code cannot express
 * lives here.
 *
 * ONE LIVE OWNER, DELIBERATELY
 * ----------------------------
 * No service here sets `configFile`. That is not an omission. Railway's IaC
 * refuses to manage a service whose `configFile` names a `railway.json` or
 * `railway.toml` — `isManagedByRepoConfig` in the SDK emits a hard error and
 * skips the resource — so a service pointed at the repo config would converge
 * once and then never again, which would quietly destroy the idempotency this
 * whole design rests on. Two owners for one setting is the bug; this file is the
 * owner, and `railway.json` is the file it reads.
 *
 * NO SECRET IS DECLARED HERE, AND NONE CAN BE
 * -------------------------------------------
 * Every credential in this project is either generated by Railway
 * (`generator: 'secret(...)'`, evaluated server-side so the value never exists
 * in this repository, in a log, or in a process argument) or referenced from
 * another service (`ref()`, which compiles to `${{Service.VAR}}` and is resolved
 * by the platform at deploy time). Nothing is copied, and there is no literal
 * secret to commit.
 *
 * PRODUCTION IS SUPPORTED, AND IS GUARDED
 * ---------------------------------------
 * `DASH.13` approved an intentional public production deployment, so this file no
 * longer refuses production outright — it refuses production that nobody asked
 * for. Evaluating against a production environment throws unless BOTH the
 * repository's standing approval (`project.productionRelease.approved`) and the
 * caller's per-invocation intent (`ARPI_RAILWAY_CONFIRM_PRODUCTION=true`, set only
 * by a tool given `--confirm-production`) are present. A stray
 * `railway config apply` linked to production supplies neither, and still fails
 * before it can stage anything.
 *
 * This is the `DASH.13` closeout's release-critical fix. The unconditional throw
 * that used to live here made the approved production path impossible: it fired
 * during the bootstrap tool's OFFLINE validation, so
 * `--environment production --confirm-production` exited 2 before a token was read.
 */
import { readFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import { defineRailway, github, postgres, ref, service } from 'railway/iac'

const HERE = dirname(fileURLToPath(import.meta.url))
const REPO = resolve(HERE, '..')

/**
 * Read a JSON file from the repository.
 *
 * `readFileSync` plus `JSON.parse` rather than an `import ... with { type:
 * 'json' }`: import attributes are not guaranteed to be supported by the
 * TypeScript runner Railway invokes, and a configuration file that fails to load
 * because of a syntax nicety is a bad trade for one line saved.
 */
function readJson<T>(relativePath: string): T {
  return JSON.parse(readFileSync(join(REPO, relativePath), 'utf8')) as T
}

/* -------------------------------------------------------------------------- */
/* The source-controlled specification                                        */
/* -------------------------------------------------------------------------- */

interface RailwayRepoConfig {
  build: {
    builder: 'NIXPACKS' | 'DOCKERFILE' | 'RAILPACK' | 'HEROKU' | 'PAKETO'
    dockerfilePath: string
    watchPatterns: string[]
  }
  deploy: {
    healthcheckPath: string
    healthcheckTimeout: number
    restartPolicyType: 'ON_FAILURE' | 'ALWAYS' | 'NEVER'
    restartPolicyMaxRetries: number
    numReplicas: number
    sleepApplication: boolean
  }
}

interface ProjectSpec {
  project: {
    name: string
    environment: string
    productionEnvironment: string
    createProductionEnvironment: boolean
    /** Absent is read as NOT approved, which is the fail-closed direction. */
    productionRelease?: { approved?: boolean }
  }
  repository: {
    slug: string
    deploymentBranch: string
    waitForCiChecks: boolean
  }
  services: {
    portfolio: { name: string }
    postgres: { name: string }
    databaseSetup: {
      name: string
      dockerfilePath: string
      restartPolicyType: 'ON_FAILURE' | 'ALWAYS' | 'NEVER'
    }
  }
}

const repoConfig = readJson<RailwayRepoConfig>('railway.json')
const spec = readJson<ProjectSpec>('deployment/railway/project.config.json')

/**
 * The alphabet and length used for every password Railway generates for this
 * project. Alphanumeric on purpose: these values travel through a PostgreSQL
 * connection URL and through `psql`, and a generated `@`, `:`, `/` or `#` would
 * need percent-encoding at every use site — which is exactly the kind of
 * intermittent, one-in-sixty-four failure that gets "fixed" by weakening the
 * generator. 48 alphanumeric characters is ~285 bits of entropy, so nothing is
 * given up by excluding punctuation.
 */
const PASSWORD_GENERATOR =
  'secret(48, "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789")'

/** Seconds Railway waits after SIGTERM before killing a container. Set as a
 *  variable rather than a deploy field, which is the mechanism Railway's own
 *  Postgres template uses. */
const DRAINING_SECONDS = '30'

export default defineRailway((ctx, project) => {
  /* ---------------------------------------------------------------------- */
  /* Guard: never touch production BY ACCIDENT                              */
  /* ---------------------------------------------------------------------- */

  /**
   * The target environment, from whichever source knows it.
   *
   * `ctx.environmentName` is populated by Railway during `config plan` and
   * `config apply` against a linked environment — that is the path that matters,
   * because it is the one that mutates a live project.
   *
   * `ARPI_RAILWAY_TARGET_ENVIRONMENT` is the second source, set by the tools in
   * `scripts/railway/`. It exists because the context is NOT populated during a
   * local `evaluate`, so without it this guard could not be exercised offline —
   * and a guard that has never been observed to fire is not a control. It is
   * asserted to fire in `tests/railway/iac-graph.test.ts`.
   */
  const targetEnvironment = (
    ctx.environmentName ??
    ctx.environment ??
    process.env['ARPI_RAILWAY_TARGET_ENVIRONMENT'] ??
    process.env['RAILWAY_ENVIRONMENT_NAME'] ??
    process.env['RAILWAY_ENVIRONMENT'] ??
    ''
  ).trim()
  const production = spec.project.productionEnvironment

  if (targetEnvironment.toLowerCase() === production.toLowerCase()) {
    /**
     * TWO independent signals, and production needs both.
     *
     * The standing approval lives in the repository and is reviewable. The
     * per-invocation confirmation is typed at a command line and expires with the
     * command. Neither alone is enough, and the environment NAME is not one of
     * them — a name is what an accident supplies.
     */
    if (spec.project.productionRelease?.approved !== true) {
      throw new Error(
        `Refusing to evaluate the ARPI Railway definition against the "${production}" ` +
          'environment: deployment/railway/project.config.json does not approve a ' +
          'production release (project.productionRelease.approved is not true). ' +
          'Approving one is a reviewable change to the repository — see ' +
          'deployment/railway/README.md section 7.'
      )
    }
    if ((process.env['ARPI_RAILWAY_CONFIRM_PRODUCTION'] ?? '').trim() !== 'true') {
      throw new Error(
        `Refusing to evaluate the ARPI Railway definition against the "${production}" ` +
          'environment without explicit per-invocation confirmation. A production ' +
          'release is approved, but approval is not intent: re-run the tool with ' +
          '--environment production --confirm-production, which is what sets ' +
          'ARPI_RAILWAY_CONFIRM_PRODUCTION. Nothing has been staged.'
      )
    }
  }

  /* ---------------------------------------------------------------------- */
  /* Postgres                                                               */
  /* ---------------------------------------------------------------------- */

  /**
   * Railway's official PostgreSQL database.
   *
   * `postgres()` resolves to the platform's `postgres-ssl` image, which
   * terminates TLS itself, and Railway's apply path attaches a persistent volume
   * at the image's default mount path and publishes a TCP proxy on 5432. None of
   * those three is configured here because none of them is ours to configure —
   * they are properties of the template — but all three are REQUIRED by this
   * project, so `scripts/railway/verify_railway_configuration.ts` asserts each
   * of them against the live service rather than assuming the template still
   * behaves as documented.
   *
   * The TCP proxy exists for one reason: a future Microsoft Fabric connection
   * opens from Microsoft's network and cannot reach Railway's private network.
   * The website never touches this database.
   */
  const db = postgres(spec.services.postgres.name)

  /* ---------------------------------------------------------------------- */
  /* The website                                                            */
  /* ---------------------------------------------------------------------- */

  const portfolio = service(spec.services.portfolio.name, {
    /**
     * GitHub source, so routine deployments are Railway's own autodeploys
     * rather than a `railway up` from CI. There is exactly one deployment owner.
     *
     * `checkSuites` is Railway's wait-for-CI: the deployment waits for the
     * commit's GitHub checks before building. That matters here because the two
     * existing workflows are the gate that proves the manifest is current and
     * the site makes no unbacked claim — deploying before they finish would
     * publish first and check afterwards.
     *
     * `rootDirectory` is deliberately NOT set. The build context must remain the
     * repository root; see the header of portfolio/Dockerfile.railway.
     */
    source: github(spec.repository.slug, {
      branch: spec.repository.deploymentBranch,
      checkSuites: spec.repository.waitForCiChecks,
    }),

    // Build and deploy configuration, read from `railway.json` rather than
    // written twice. A change to watch paths or the health check is therefore a
    // one-file change, reviewable in a diff, and applied by `railway config
    // apply`.
    build: {
      builder: repoConfig.build.builder,
      dockerfilePath: repoConfig.build.dockerfilePath,
      watchPatterns: repoConfig.build.watchPatterns,
    },
    deploy: {
      healthcheckPath: repoConfig.deploy.healthcheckPath,
      healthcheckTimeout: repoConfig.deploy.healthcheckTimeout,
      restartPolicyType: repoConfig.deploy.restartPolicyType,
      restartPolicyMaxRetries: repoConfig.deploy.restartPolicyMaxRetries,
      numReplicas: repoConfig.deploy.numReplicas,
      sleepApplication: repoConfig.deploy.sleepApplication,
    },

    /**
     * TWO VARIABLES, BOTH NON-SECRET LITERALS, NEITHER TYPED BY A HUMAN.
     *
     * There is no `ARPI_SITE_URL` and no `NEXT_PUBLIC_SITE_URL` here. The site
     * derives its canonical origin from the platform's own
     * `RAILWAY_PUBLIC_DOMAIN`, which the Dockerfile consumes through an `ARG` of
     * the same name — so the deployment's URL is never copied, never typed, and
     * cannot be stale.
     *
     * There is no database variable of any kind, and that absence is asserted:
     * `verify_railway_configuration.ts` fails if a `DATABASE_*`, `PG*` or
     * password variable ever appears on this service.
     */
    env: {
      // The case-study gate's build flag, stated explicitly rather than left to
      // absence. It is one of five conditions and the other four are statements
      // about work that has not been done, so this cannot unlock anything — but
      // an operator reading the Railway dashboard should see the gate closed,
      // not have to infer it from a variable that is not there.
      NEXT_PUBLIC_ARPI_CASE_STUDY_ENABLED: 'false',

      // Graceful termination, so an in-flight response is not cut off by a
      // deployment. The container's CMD uses `exec`, so node is PID 1 and
      // receives the SIGTERM this window belongs to.
      RAILWAY_DEPLOYMENT_DRAINING_SECONDS: DRAINING_SECONDS,
    },

    /**
     * Public HTTP is required, but the Railway-generated domain is NOT declared
     * here.
     *
     * A generated domain's name is chosen by Railway and is not knowable in
     * advance, so it cannot appear in a declarative file without hard-coding a
     * value this repository does not own. `domains: [...]` is for a custom
     * domain, and there is none. Generation is therefore done once, idempotently,
     * by `scripts/railway/bootstrap_railway.ts`, which lists the service's
     * domains first and creates one only when none exists — and does it BEFORE
     * triggering the first deployment, so `RAILWAY_PUBLIC_DOMAIN` is already
     * populated when the build reads it.
     */
  })

  /* ---------------------------------------------------------------------- */
  /* One-time database provisioning job                                     */
  /* ---------------------------------------------------------------------- */

  /**
   * The provisioning job.
   *
   * WHY A JOB SERVICE AND NOT A CI STEP
   * A GitHub Actions runner would have to reach PostgreSQL over the public TCP
   * proxy, which means the workflow handling a live database superuser URL and
   * the database needing public exposure for the build. Inside Railway the job
   * reaches PostgreSQL over the project's PRIVATE network using reference
   * variables the platform resolves at deploy time: no credential leaves
   * Railway, none passes through GitHub, and the public proxy is needed only
   * later, for Fabric.
   *
   * WHY IT IS NOT A BACKEND
   * It serves no traffic, has no public domain, has no health check, and its
   * restart policy is NEVER — so a run that completes is not restarted into a
   * loop, which is the failure mode that turns a one-time job into a permanent
   * service nobody meant to create.
   */
  const databaseSetup = service(spec.services.databaseSetup.name, {
    source: github(spec.repository.slug, {
      branch: spec.repository.deploymentBranch,
    }),
    build: {
      builder: 'DOCKERFILE',
      dockerfilePath: spec.services.databaseSetup.dockerfilePath,
      // Rebuild only when the database layer, the loader, or the job itself
      // changes. A website commit must not re-run a data load.
      watchPatterns: [
        'sql/**',
        'src/arpi/**',
        'config/**',
        'scripts/verify_cloud_database.py',
        'deployment/railway/Dockerfile.database-setup',
        'deployment/railway/provision_database.sh',
        'pyproject.toml',
        // The image installs `uv sync --frozen`, so a lock change genuinely changes
        // what this job runs. Without this pattern a dependency update would ship to
        // Railway only on the next unrelated `src/arpi/**` commit.
        'uv.lock',
      ],
    },
    deploy: {
      // NEVER, not ON_FAILURE. A failed provisioning run must be read and fixed,
      // not retried against a half-built database.
      restartPolicyType: spec.services.databaseSetup.restartPolicyType,
      numReplicas: 1,
    },

    env: {
      /* ------------------------------------------------------------------ */
      /* Reference variables. Nothing below is a copied value.              */
      /* ------------------------------------------------------------------ */

      // `db.env.X` and `ref(db, 'X')` both compile to a Railway reference —
      // `${{Postgres.X}}` — which the platform resolves at deploy time. The
      // typed accessor is preferred because a misspelled variable name is a
      // compile error here, whereas a hand-written `${{Postgres.DATABSE_URL}}`
      // would deploy successfully and resolve to that literal text.
      DATABASE_URL: db.env.DATABASE_URL,

      // libpq equivalents, so `psql` and psycopg agree with each other without
      // either of them parsing the URL.
      PGHOST: ref(db, 'RAILWAY_PRIVATE_DOMAIN'),
      PGPORT: db.env.PGPORT,
      PGDATABASE: db.env.PGDATABASE,
      PGUSER: db.env.PGUSER,
      PGPASSWORD: db.env.PGPASSWORD,

      // The external connection details for the eventual Fabric handoff.
      // Referenced rather than hardcoded: the proxy's host and port are assigned
      // by Railway and change if the proxy is recreated.
      ARPI_TCP_PROXY_DOMAIN: ref(db, 'RAILWAY_TCP_PROXY_DOMAIN'),
      ARPI_TCP_PROXY_PORT: ref(db, 'RAILWAY_TCP_PROXY_PORT'),

      /* ------------------------------------------------------------------ */
      /* Generated secrets. Generated by Railway, not by this repository.    */
      /* ------------------------------------------------------------------ */

      // `generator` is evaluated server-side by Railway, exactly as Railway's
      // own Postgres template generates `POSTGRES_PASSWORD`. The consequence
      // matters: the value never exists in this repository, never appears in a
      // process argument, never reaches a log, and is not known to the bootstrap
      // tool or to GitHub Actions. It is created once and is not rotated by a
      // subsequent apply.
      //
      // Login role for the loader. Holds `arpi_loader`.
      ARPI_PIPELINE_PASSWORD: { generator: PASSWORD_GENERATOR },

      // Login role for the semantic model. Holds `arpi_reporter` and nothing
      // else, so it is provably confined to the `reporting` schema. THIS is the
      // one credential a human later copies out of Railway into Microsoft
      // Fabric, through a browser, by hand — see deployment/railway/README.md
      // section 8. It is deliberately not rotated on every deployment: doing so
      // would break a configured Fabric connection on an unrelated commit.
      ARPI_FABRIC_PASSWORD: { generator: PASSWORD_GENERATOR },

      /* ------------------------------------------------------------------ */
      /* Non-secret literals                                                */
      /* ------------------------------------------------------------------ */

      // The deterministic profile. The seed (20250701) and the reporting window
      // come from config/development.yaml, not from here, so the profile cannot
      // be half-overridden by a deployment variable.
      ARPI_PROFILE: 'development',
      ARPI_DATABASE__ENABLED: 'true',

      // TLS required for the loader's own connection. The provisioning script
      // additionally asserts the session is encrypted by reading `pg_stat_ssl`,
      // because a value in a variable proves nothing about the session that was
      // actually opened.
      ARPI_DATABASE__SSLMODE: 'require',

      // The job converges: it applies the idempotent SQL sequence and
      // re-verifies. It never drops or recreates the database.
      ARPI_PROVISION_MODE: 'converge',

      RAILWAY_DEPLOYMENT_DRAINING_SECONDS: DRAINING_SECONDS,
    },
  })

  return project(spec.project.name, {
    // Only the target environment is declared. `production` is absent on
    // purpose: declaring it would create it.
    environments: [spec.project.environment],
    resources: [portfolio, db, databaseSetup],
  })
})
