-- =============================================================================
-- File:            sql/05_reporting/00_reporting_scope.sql
-- Project:         Automotive Retail Performance Intelligence (ARPI)
-- Purpose:         Record the deliberate scope of the reporting layer — which views exist, which are deliberately absent, and why.
-- Execution order: Reporting layer, first file.
-- Idempotency:     Fully idempotent. Documentation only; the single statement is a COMMENT ON SCHEMA.
-- Ownership:       n/a (comment applied by the bootstrap superuser; schema ownership moves to arpi_admin in sql/07_security/01_grants.sql).
-- Grain:           n/a (documentation only)
-- =============================================================================
--
-- =============================================================================
-- WHAT THE REPORTING LAYER CONTAINS  (status: Implemented — 39 views:
-- 28 MVP + 6 sanitized public listing lane + 5 dashboard program)
-- =============================================================================
-- DIMENSION VIEWS — one per MVP dimension. Each relates one-to-many into the
-- facts, in a single direction, and each dimension key is unique so no
-- relationship is ever forced into many-to-many.
--
--   vw_calendar               one row per calendar date  (the marked date table)
--   vw_dealership             one row per CURRENT dealership store version
--   vw_employee               one row per CURRENT employee version, minimised
--   vw_customer               one row per customer, banded attributes only
--   vw_vehicle                one row per physical vehicle
--   vw_vehicle_model          one row per model line
--   vw_lead_source            one row per normalised lead source
--   vw_marketing_campaign     one row per campaign
--
-- FACT VIEWS — one per MVP fact, at the fact's own grain. No aggregation, no
-- filtering, no row lost; RECON-REPORT-*-ROWS reconciles each one to its fact on
-- every run.
--
--   vw_vehicle_sales          one row per finalized vehicle transaction
--   vw_inventory_snapshots    one row per vehicle per store per snapshot date
--   vw_leads                  one row per CRM lead, duplicates included
--   vw_appointments           one row per scheduled appointment
--   vw_marketing_spend        one row per store x campaign x month
--
-- GOVERNED ANALYTICAL VIEWS — each owns the SQL side of one or more KPIs at a
-- declared grain, publishing numerators and denominators as separate additive
-- columns.
--
--   vw_sales_summary          KPI-SLS-001..003, KPI-INV-007 mean
--   vw_gross_summary          KPI-GRS-001..006
--   vw_inventory_health       KPI-INV-001..006
--   vw_inventory_aging        the age distribution behind KPI-INV-004
--   vw_days_to_sale           KPI-INV-007
--   vw_inventory_turn         KPI-INV-008
--   vw_days_supply            KPI-INV-009
--   vw_lead_funnel            KPI-FUN-001, 002, 003, 006
--   vw_appointment_funnel     KPI-FUN-004, 005
--   vw_lead_response          KPI-FUN-007, 008
--   vw_marketing_performance  KPI-MKT-001..003
--   vw_data_quality_trend     quality across runs
--   vw_reconciliation_status  reconciliation evidence, without a grant on audit
--
-- OPERATIONAL VIEWS — run context for the Data Quality page.
--
--   vw_pipeline_run_summary   one row per pipeline run, with counts
--   vw_data_quality_summary   one row per validation result, with run context
--
-- Those twenty-eight are the MVP surface: what the SQL baseline was measured
-- against and what the Power BI semantic model binds to. Two further lanes exist
-- in the same schema and are held apart from it on purpose, because folding either
-- in would change a number measured against a specific baseline run while the
-- semantic model — still awaiting real-engine validation — gained nothing.
--
-- SANITIZED PUBLIC LISTING LANE (ADR-0011) — six views over
-- warehouse.fact_vehicle_listing_snapshot and warehouse.dim_observed_vehicle,
-- populated by a workbook import rather than by a pipeline run.
--
--   vw_vehicle_listing_current             one row per currently-listed vehicle
--   vw_vehicle_listing_summary             listing counts and price completeness
--   vw_vehicle_listing_model_mix           listing mix by model line
--   vw_vehicle_listing_price_completeness  how much of the lane carries a price
--   vw_vehicle_listing_observation_span    the window each vehicle was observed
--   vw_vehicle_listing_change              listing-to-listing change
--
-- DASHBOARD PROGRAM LANE — five views added by DASH.3, DASH.4 and DASH.5 for the
-- Dealer Operations Command Center. Four of them read the same warehouse facts as
-- the MVP surface and add no new fact; the fifth reads warehouse.fact_sales_target,
-- the one fact this lane owns. They exist because ADR-0013 condition 2 puts
-- analytical arithmetic in SQL rather than in the console.
--
--   vw_sales_gross_trend      store x sale date: volume and gross on one row, with
--                             their condition and sale-type components as additive
--                             columns rather than as extra rows
--   vw_gross_change_bridge    store x month pair x component: the volume, front-PVR
--                             and back-PVR decomposition of total-gross change,
--                             published as exact numerators over a shared
--                             denominator so the identity needs no division
--   vw_deal_explorer          one row per finalized transaction, public-safe and
--                             compact, for the Deal Explorer index
--   vw_deal_jacket            one row per finalized transaction, presentation-
--                             complete: the cost components behind the front gross,
--                             the trade context, the finance amounts, the people and
--                             the lead's paper trail, for the Deal Jacket route
--   vw_target_attainment      store x target month x target scope x targeted KPI:
--                             the monthly operating PLAN beside the month-to-date
--                             ACTUAL, with the selling-day arithmetic KPI-TGT-001
--                             through KPI-TGT-010 are computed from. Attainment and
--                             pace are published as numerator and denominator pairs,
--                             never as a bare ratio, so a group figure is
--                             SUM(numerator) / SUM(denominator) and no consumer can
--                             average a percentage. The selling-day denominator
--                             comes from warehouse.dim_date.is_selling_day and from
--                             nowhere else (ADR-0002), and the as-of date is the
--                             governed dataset as-of, never current_date
--
-- arpi_reporter can read these thirty-nine views and nothing else. The expected
-- set is fixed in arpi.constants.REPORTING_VIEWS, and
-- tests/integration/test_reporting_layer_completeness.py asserts the schema
-- contains exactly those and no others — a view added here and not declared there
-- fails the build rather than appearing silently.
--
-- =============================================================================
-- WHAT IS DELIBERATELY ABSENT  (status: Deferred)
-- =============================================================================
--   reporting.vw_service_summary        needs warehouse.fact_service_visit
--   an F&I product-detail view          needs warehouse.fact_finance_product_sale
--
-- reporting.vw_target_attainment WAS on this list and is no longer: DASH.5 promoted
-- warehouse.fact_sales_target from Deferred to Implemented and built the view over
-- it. See DATA_DICTIONARY.md section 41.
--
-- REASON. Both remaining underlying facts are Deferred (DATA_DICTIONARY.md
-- section 27).
-- A view over a non-existent table cannot be created at all, and a view returning
-- a correctly-shaped but permanently empty result set would be worse than nothing:
-- it would let a Power BI model bind to a KPI that has never been computed. The
-- stakeholder questions those three facts block are recorded in
-- docs/requirements/STAKEHOLDER_QUESTIONS.md section 6 rather than left absent.
--
-- =============================================================================
-- REPORTING LAYER RULES
-- =============================================================================
--   1. Every reporting object is a view. No physical reporting table exists; if a
--      materialised view is ever needed it must be justified by a MEASURED
--      performance problem, not an anticipated one.
--   2. Views are owned by arpi_admin and read warehouse and audit objects that
--      arpi_admin also owns, so arpi_reporter needs no privilege on those schemas.
--      That is the mechanism which keeps Power BI out of the raw layer.
--   3. Column names are business-facing and stable. Renaming a warehouse column
--      must not change a reporting column; the view absorbs the change.
--   4. Column names remain lower_snake_case and unquoted so that psql, Power BI
--      and Excel all address them the same way; consumer tools apply formatting.
--   5. Every view declares its grain in COMMENT ON VIEW, and every column carries
--      a COMMENT ON COLUMN. Both are asserted by the integration suite.
--   6. A fact view preserves its fact's grain exactly. Where one joins a dimension
--      to derive a column, the row count is reconciled on every run.
--   7. A ratio's numerator and denominator are published as separate ADDITIVE
--      columns. Where a ratio column exists it is valid at that view's grain only,
--      and a semantic model must divide in DAX so the result recomputes.
--   8. A zero denominator yields NULL, never zero and never infinity.
--   9. Row-level values are exposed wherever a median is specified, because an
--      order statistic cannot be recomputed from an aggregate.
--  10. No prohibited or sensitive field appears. Age is a band, geography is
--      county and market area, and no name, contact detail, pay field or
--      communication content exists anywhere in ARPI.

COMMENT ON SCHEMA reporting IS
    'ARPI reporting layer. The only schema Power BI, Excel and arpi_reporter may read, and the only schema '
    'they need: 39 views in three lanes. The MVP surface is 28 -- all eight MVP dimensions, all five MVP '
    'facts at their own grain, thirteen governed analytical views owning the SQL side of all 29 KPIs, and '
    'two operational views -- and it is what the SQL baseline was measured against and what the semantic '
    'model binds to. Beside it sit six sanitized public listing views (ADR-0011) and five dashboard '
    'program views (DASH.3, DASH.4, DASH.5), both lanes held apart from the MVP count on purpose so that adding them '
    'cannot silently move a measured baseline. Every view '
    'declares its grain and comments every column; every ratio publishes its numerator and denominator as '
    'separate additive columns and returns NULL on an empty denominator; row-level values are exposed '
    'wherever a median is specified. Service and F&I product views are deliberately '
    'absent because their facts are Deferred; target attainment was on that list until DASH.5 promoted '
    'warehouse.fact_sales_target. See sql/05_reporting/00_reporting_scope.sql.';
